### ISSUE TITLE
Add masking library to NPMap.js

### ISSUE THREAD

**Issue by MappingKat** [nationalparkservice/npmap.js#132]
preinit: function(callback) {

      // http://ebrelsford.github.io/Leaflet.snogylop
      (function() {
        function d(a) {
          var d = [a.latLng([90, 470]), a.latLng([90, -470]), a.latLng([-90, -470]), a.latLng([-90, 470])];
          a.extend(a.Polygon.prototype, {
            initialize: function(e, b) {
              if (b.invert && !b.invertMultiPolygon) {
                var c = [];
                c.push(d);
                c.push(e[0]);
                e = c
              }
              a.Polyline.prototype.initialize.call(this, e, b);
              this._initWithHoles(e)
            },
            getBounds: function() {
              return this.options.invert ? new a.LatLngBounds(this._holes) : new a.LatLngBounds(this.getLatLngs())
            }
          });
          a.extend(a.MultiPolygon.prototype, {
            initialize: function(a, b) {
              this._layers = {};
              this._options = b;
              if (b.invert) {
                b.invertMultiPolygon = !0;
                var c = [];
                c.push(d);
                for (var f in a) c.push(a[f][0]);
                a = [c]
              }
              this.setLatLngs(a)
            }
          })
        }
        "function" === typeof define && define.amd ? define(["leaflet"], function(a) {
          d(a)
        }) : d(L)
      })();

**Comment by nateirwin** [comment]
Think we'll just add this as a supported plugin. I'm going to add this to the next milestone.

**Comment by nateirwin** [comment]
This is now a supported plugin. It can be loaded from here:

http://www.nps.gov/lib/npmap.js/3.0.12/plugins/Leaflet.Snogylop/0.2.0/plugin.js
