### ISSUE TITLE
Change Measure Control Units

### ISSUE THREAD

**Issue by jduggan1** [nationalparkservice/npmap.js#183]
We would like to add the ability to select the measurement units in the measure control (ie, use metric units instead of miles, acres, etc.).

**Comment by nateirwin** [comment]
@MappingKat is actually working on this right now. We’ll have an update shortly.

**Comment by nateirwin** [comment]
Ok, this is ready to go and documented in API.md: https://github.com/nationalparkservice/npmap.js/blob/master/API.md#lnpmapmeasurecontrolconfig-object.
