### ISSUE TITLE
Clustering error in API version

### ISSUE THREAD

**Issue by ldnash** [nationalparkservice/npmap.js#191]
I keep getting an error thrown when trying to use clustering on a layer with points using the API (rather than the Bootstrap version). I put together a quick demonstration based on your helpful "Styling Vectors" documented example. The points load fine (without clustering if you comment out the cluster option on line 39:

http://ldnash.github.io/saan/clusterbug/

**Comment by nateirwin** [comment]
Thanks for reporting! This is now fixed and the new version of NPMap.js is deployed. It may take a few minutes to update on our CDN.
