### ISSUE TITLE
Default colors for edit and measure controls

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/npmap.js#193]
The attached screenshot shows the current defaults (pink for edit and red for measure). These colors can be overridden in NPMap.js, but it would be good to have a set of defaults that works well together and across different types of basemaps.

![edit_control___examples___npmap_js](https://cloud.githubusercontent.com/assets/10443/6251203/d0833e62-b74f-11e4-8a0a-893a4d92465f.png)

**Comment by nateirwin** [comment]
More/better screenshots. The first is all of the edit shapes (markers, lines, and polygons). The second is the measure shapes (lines and polygons).

![edit_control___examples___npmap_js](https://cloud.githubusercontent.com/assets/10443/6251337/93ab53de-b750-11e4-9fb4-8e4685d05af7.png)

![edit_control___examples___npmap_js](https://cloud.githubusercontent.com/assets/10443/6251351/af9d1a46-b750-11e4-993f-44a66943bf24.png)

**Comment by makella** [comment]
### Editor Shape Colors
I think there are two colors that will work across multiple basemaps and keep with our colorblind requirement.  Both colors need slight adjustment in their default properties which are outlined in more detail below:

#### __#fa946e__

__Point:__
Default marker size: medium

__Line:__
Default line width: 4 pt
Default opacity: 1

__Polygon:__
Default opacity: 0.4
Default outline width: 4 pt
Default outline opacity: 1

Here are some samples of what this color looks like across multiple basemaps at both small and large scales:
#### Small Scales
![screen shot 2015-02-18 at 1 49 39 pm](https://cloud.githubusercontent.com/assets/1566273/6256496/f710aef4-b775-11e4-9bfb-9be63bfb709d.png)
![screen shot 2015-02-18 at 1 49 54 pm](https://cloud.githubusercontent.com/assets/1566273/6256501/fdf46ad0-b775-11e4-9022-d5caea63d455.png)
![screen shot 2015-02-18 at 1 50 13 pm](https://cloud.githubusercontent.com/assets/1566273/6256503/0169020c-b776-11e4-84c7-7e945cb5388d.png)
![screen shot 2015-02-18 at 1 50 54 pm]
![screen shot 2015-02-18 at 1 50 54 pm](https://cloud.githubusercontent.com/assets/1566273/6256513/15944250-b776-11e4-84e1-b1addbfa794b.png)

#### Large Scales
![screen shot 2015-02-18 at 1 55 33 pm](https://cloud.githubusercontent.com/assets/1566273/6256541/5b1b2834-b776-11e4-9d75-8876bbc97432.png)
![screen shot 2015-02-18 at 1 55 46 pm](https://cloud.githubusercontent.com/assets/1566273/6256525/2ae2102e-b776-11e4-958c-a5c322933c38.png)
![screen shot 2015-02-18 at 1 51 50 pm](https://cloud.githubusercontent.com/assets/1566273/6256523/25e90d70-b776-11e4-95fb-9fe1ca159938.png)
![screen shot 2015-02-18 at 2 00 33 pm](https://cloud.githubusercontent.com/assets/1566273/6256570/913026b8-b776-11e4-9731-d0d7c3a3d8f4.png)
![screen shot 2015-02-18 at 1 52 10 pm](https://cloud.githubusercontent.com/assets/1566273/6256526/2f1c708a-b776-11e4-9b00-d679bf9aa31c.png)
![screen shot 2015-02-18 at 1 52 23 pm](https://cloud.githubusercontent.com/assets/1566273/6256528/32bf437a-b776-11e4-8d75-8497cb2da6bc.png)

#### __#d46655__

__Point:__
Default marker size: medium

__Line:__
Default line width: 4 pt
Default opacity: 1

__Polygon:__
Default opacity: 0.4
Default outline width: 4 pt
Default outline opacity: 1

Here are some samples of what this color looks like across multiple basemaps at both small and large scales:

#### Small Scale
![screen shot 2015-02-18 at 2 05 35 pm](https://cloud.githubusercontent.com/assets/1566273/6256814/70284d0e-b778-11e4-8338-0a11cef4e709.png)
![screen shot 2015-02-18 at 2 05 54 pm](https://cloud.githubusercontent.com/assets/1566273/6256816/74f321f6-b778-11e4-9de1-3f5917f09f0f.png)
![screen shot 2015-02-18 at 2 06 12 pm](https://cloud.githubusercontent.com/assets/1566273/6256822/7b8a5048-b778-11e4-8858-8da80c762225.png)
![screen shot 2015-02-18 at 2 06 41 pm](https://cloud.githubusercontent.com/assets/1566273/6256852/b0b094da-b778-11e4-97fb-4c87bcebeb79.png)

#### Large Scale
![screen shot 2015-02-18 at 2 18 30 pm](https://cloud.githubusercontent.com/assets/1566273/6256897/283eb8ec-b779-11e4-9b16-c12cb985ceda.png)
![screen shot 2015-02-18 at 2 18 39 pm](https://cloud.githubusercontent.com/assets/1566273/6256907/38e1ed54-b779-11e4-946f-9dfa61caf8bd.png)
![screen shot 2015-02-18 at 2 18 50 pm](https://cloud.githubusercontent.com/assets/1566273/6256909/3de8061c-b779-11e4-9002-14c3bb7064c6.png)
![screen shot 2015-02-18 at 2 19 07 pm](https://cloud.githubusercontent.com/assets/1566273/6256925/5c41161c-b779-11e4-8a37-e6ac045c9ed6.png)
![screen shot 2015-02-18 at 2 17 16 pm](https://cloud.githubusercontent.com/assets/1566273/6256929/629640b4-b779-11e4-9b94-20544a98985d.png)
![screen shot 2015-02-18 at 2 17 25 pm](https://cloud.githubusercontent.com/assets/1566273/6256933/676bedb4-b779-11e4-81d4-7b71bb71d697.png)
![screen shot 2015-02-18 at 2 18 00 pm](https://cloud.githubusercontent.com/assets/1566273/6256941/6eeba6ce-b779-11e4-9cab-de9c84165077.png)

**Comment by makella** [comment]
I'll work on the measure color next.  Thinking that it should be something that contrasts against the edit shape color if a user is performing both operations on one map.

**Comment by nateirwin** [comment]
Thanks! I supposed we could use the same colors for both, but it is probably better to have two colors.

**Comment by nateirwin** [comment]
Not sure we can change colors based on zoom level. That may be something we can do in the future, but which one should we go with for now?

**Comment by makella** [comment]
We don't need to change colors based on zoom level... the main point here was just showing two colors that work well across multiple basemaps at multiple scales so no prob on that.  I think the default symbology should change to what I outlined above with outline width, opacity, and marker size to help better highlight the information being added to the map.  A future option to edit symbology on the fly would be awesome too.  

I don't really have a preference which color we go with but for decision making sake, let's go with __#d46655__ and the following modifications to the defaults when editing (if that is possible):

__Point:__
Default marker size: medium

__Line:__
Default line width: 4 pt
Default opacity: 1

__Polygon:__
Default opacity: 0.4
Default outline width: 4 pt
Default outline opacity: 1

**Comment by nateirwin** [comment]
The styles for the edit control have been updated. I'll update the measure control styles whenever you are ready. Thanks!

![edit_control___examples___npmap_js](https://cloud.githubusercontent.com/assets/10443/6272192/1cb69a8a-b823-11e4-8266-f1a9690a05e9.png)

**Comment by makella** [comment]
Ok, great.  How about we try #882255 for measuring.

**Comment by nateirwin** [comment]
Done. Closing now. Thanks!

![edit_control___examples___npmap_js](https://cloud.githubusercontent.com/assets/10443/6272567/d633295e-b825-11e4-83a0-31f406556833.png)
