### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by ryanjhodge** [nationalparkservice/npmap.js#202]
Noticed that npmap.js will successfully build in Windows but tests fail.  The dist/examples will not load either.

![grunttest](https://cloud.githubusercontent.com/assets/4172213/7326248/d81dddb0-ea78-11e4-8b1d-abd1943ed6b6.PNG)

[These guys](https://github.com/stackgl/shader-school/issues/58) seemed to have a similiar issue and it looks like upgrading browserify/brfs to a later version worked for them.  Tried that but it caused a whole slew of dependency issues.

**Comment by nateirwin** [comment]
Interesting. Not sure what this is, but honestly I've never tried to build on Windows :-( I'll try to find some time to look into the problem, but this isn't going to be top priority for me right now.

I am curious what you mean when you say: "The dist/examples will not load either." You mean load in a browser? If so, are there specific examples that won't load?

**Comment by ryanjhodge** [comment]
Hey no rush at all, I use Linux :penguin: (at home). Just thought I'd let you guys know.

About the dist/examples, yeah none of them load in the browser they all throw this same error:

`fs.readFileSync is not a function`

![capture](https://cloud.githubusercontent.com/assets/4172213/7383477/d664cbd2-edd4-11e4-9f21-068935a84125.PNG)

**Comment by ryanjhodge** [comment]
nationalparkservice/npmap.js@a3025c83b768e724206bd00f8b6007dbae6ba56e resolves issue and is building on Windows 8.1 x64 and node v0.12

**Comment by nateirwin** [comment]
Merging now. Thanks!
