### ISSUE TITLE
Switch Mapbox presets to `mapbox.x` ids

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/npmap.js#205]
This is done, but we need to verify with @phoefflernps that he is not using these ids. Once verified, we can remove the following ids from our Mapbox account:

nps.kp1dmflo
nps.kp1ekci6
nps.kp1e5gmg
nps.map-sligp1fr
nps.i49i583a
nps.kp1cjdgg
nps.kp9mndj7
nps.map-n9nxe12m
nps.map-r3ilza09
nps.map-06dnxzq5

Here’s the commit: https://github.com/nationalparkservice/npmap.js/commit/6a76de2.

**Comment by nateirwin** [comment]
Looping @makella in on this, as well. Will this help with the fifty limit problem we've run into with our Mapbox account?

**Comment by makella** [comment]
Unfortunately, no! The id's above are Projects... We're running into the 50 limit with Styles.

Once @phoefflernps let's us know, I'd be happy to delete these.

**Comment by phoefflernps** [comment]
I've pulled the codes for the base maps we have in Portal; AGOL should be similar. I'll be over today and/or tomorrow if you'd like to discuss as there seems to be quite a bit of overlap.
PT: v3/nps.2yxv8n84 (is not using a token)
PT Slate: v4/nps.68926899
PT Imagery: v4/nps.gdipreks
Other MapBox baselayers:
v4/nps.kp9mndj7
v4/nps.kp1dmflo
v4/nps.kp1ekci6
v4/nps.kp1e5gmg
v3/nps.map-n9nxe12m (no token)
v4/nps.kp1cjdgg
v3/nps.map-06dnxzq5 (no token)
v4/nps.map-lj6szvbq

**Comment by nateirwin** [comment]
@phoefflernps: Sorry to be out of touch about this. It would be great to finish this up so we can clean up our Mapbox account. Do you have time this week to work on the ArcGIS Portal/Online piece?

**Comment by nateirwin** [comment]
This is done.
