### ISSUE TITLE
Baselayers can zoom to greater zoom levels than what is set in `maxZoom`

### ISSUE THREAD

**Issue by ryanjhodge** [nationalparkservice/npmap.js#207]
Baselayers with the `maxZoom` property set in [src/prests/baselayer.json](https://github.com/nationalparkservice/npmap.js/blob/master/src/preset/baselayers.json) are still able to be zoomed past `maxZoom`

`minZoom` seems to be working as expected and if I understand correctly, the baselayer preset properties get passed in [here](https://github.com/nationalparkservice/npmap.js/blob/master/src/map.js#L197), so maybe the maxZoom property of the map is getting set somewhere else and overriding the baselayer settings? Or maybe the previously selected basemap sets the map's maxZoom? I poked around but couldn't find anything in the code to support these theories.

To reproduce, switch to Landsat Live and try to zoom past level 12.

**Comment by nateirwin** [comment]
Yes, I've noticed this too. Probably need to dive a bit deeper into this. We are setting maxZoom on the map if it isn't passed in (https://github.com/nationalparkservice/npmap.js/blob/master/src/map.js#L752), and maybe that is affecting this? If that is the case, what we need to do is update `map.maxZoom` when a baselayer is toggled on.
