### ISSUE TITLE
Module width issues with Bootstrap tabs

### ISSUE THREAD

**Issue by MappingKat** [nationalparkservice/npmap.js#215]
![screen shot 2015-06-19 at 2 47 05 pm](https://cloud.githubusercontent.com/assets/1077436/8262791/4ace2898-1692-11e5-805d-d1dbb59123d3.png)

The tabs fit when it is given a width of 298px, but when you tell it a width of 300 in the module object the tabs do not fit.

**Comment by nateirwin** [comment]
I believe this has to do with the scrollbar showing up, taking up space (~15px), and forcing the tabs to run over. This is something that should be handled in the custom code - or possibly by Bootstrap if there is a bug. Closing for now.
