### ISSUE TITLE
#223 breaks Yellowstone Roads layer in CartoDB Layer Example

### ISSUE THREAD

**Issue by ryanjhodge** [nationalparkservice/npmap.js#227]
New cartodb query in #223 causes [error](https://nps-yell.cartodb.com/api/v1/map?config=%7B%22layers%22%3A%5B%7B%22options%22%3A%7B%22sql%22%3A%22SELECT%20the_geom%2Cfmss%2Cname_segment%2Cname%2Ccreated_by%2Cupdated_by%2Cnpmap_id%2Ccartodb_id%2Cto_char(created_at%2C%20%27YYYY-MM-DD-THH24%3AMI%3ASS%20TZ%27)%20AS%20created_at%2Cto_char(updated_at%2C%20%27YYYY-MM-DD-THH24%3AMI%3ASS%20TZ%27)%20AS%20updated_at%2Cthe_geom_webmercator%2Ccartodb_id%2Cname%2Cdescription%2Cto_char(created_at%2C%20%27YYYY-MM-DD-THH24%3AMI%3ASS%20TZ%27)%20AS%20created_at%2Cto_char(updated_at%2C%20%27YYYY-MM-DD-THH24%3AMI%3ASS%20TZ%27)%20AS%20updated_at%2Cthe_geom%2Cthe_geom_webmercator%2Cplaces_id%2Ctype%2Cunit_code%2Cversion%20FROM%20roads%3B%22%2C%22cartocss%22%3A%22%23layer%7Bline-color%3A%23d39800%3Bline-opacity%3A0.8%3Bline-width%3A3%7D%22%2C%22cartocss_version%22%3A%222.1.1%22%2C%22interactivity%22%3A%5B%22fmss%22%2C%22name_segment%22%2C%22name%22%2C%22created_by%22%2C%22updated_by%22%2C%22npmap_id%22%2C%22cartodb_id%22%2C%22created_at%22%2C%22updated_at%22%2C%22cartodb_id%22%2C%22name%22%2C%22description%22%2C%22created_at%22%2C%22updated_at%22%2C%22places_id%22%2C%22type%22%2C%22unit_code%22%2C%22version%22%5D%7D%2C%22type%22%3A%22cartodb%22%7D%5D%2C%22version%22%3A%221.0.1%22%7D)

>This code is not working with the `roads` table of the `nps-yell` cartodb account (which is used in the cartodb layer example).  The query with the the [cartodb-postgresql extension](https://github.com/CartoDB/cartodb-postgresql/wiki) functions returns extra columns that the "Select All" query does not. The cartodb map api call [here](https://github.com/nationalparkservice/npmap.js/blob/cartodb-date-fields/src/layer/cartodb.js#L163) is failing because these "extra" columns are not found.

>See the query responses below:
1. [`select * from roads limit 0`](https://nps-yell.cartodb.com/api/v2/sql?q=select * from roads limit 0)
2. [`SELECT CDB_ColumnNames,CDB_ColumnType('roads',cdb_columnnames) FROM CDB_ColumnNames('roads')`](https://nps-yell.cartodb.com/api/v2/sql?q=SELECT CDB_ColumnNames,CDB_ColumnType('roads',cdb_columnnames) FROM CDB_ColumnNames('roads'))
  * For example, the `name`, `cartodb_id`, `the_geom`, `the_geom_webmercator` columns are repeated, and there are extra fields (such as `description`) that do not show up in the "Select All" query.

**Comment by nateirwin** [comment]
Yep, noticed this and started working on it yesterday afternoon. Seems like we can't get around doing both queries, right? I'm going to rope @jimmyrocks in on this in case of he knows of a fancy query that gets us exactly what we need.

**Comment by nateirwin** [comment]
Or we can switch back to just the `select * from roads limit 0` query, but that won't be as granular, correct?

**Comment by ryanjhodge** [comment]
Correct. The other query differentiates between `timestamp with timezone` and `timestamp without timezone`

Do you think it could be something to do with how that `roads` table is defined on the cartoDB side? Maybe it's a query across multiple tables? Which might explain why there are duplicate `cartodb_id`, `the_geom` fields.

**Comment by nateirwin** [comment]
Just got this back from CartoDB support. I'm going to give it a try:

`https://{your_acct_name}.cartodb.com/api/v2/sql?q=SELECT * FROM information_schema.columns WHERE table_name = '{your_dataset_name}'&api_key={your_api_key}`

**Comment by jimmyrocks** [comment]
CartoDB automatically creates the column "description" when you create a table. I probably deleted this shortly after creating the table through their UI. This change may not have been picked up in the CDB_ColumnNames table. I could always add the description column back and leave it blank.

The roads table is essentially a materialized view, made by this query:
https://github.com/nationalparkservice/cron-tasks/blob/master/tasks/places-sync/sql/cartodb/line/views/roads.sql

**Comment by nateirwin** [comment]
After consulting with @jimmyrocks on this, we're pretty sure this is a bug with the CDB_ColumnNames function. We are in the process of opening a ticket with CartoDB about the issue. I'll report back here when we hear back from them.

**Comment by nateirwin** [comment]
CartoDB verified that this is a bug in their SQL. I'm going to revert the last pull request and we can fix this when the bug is fixed.

**Comment by nateirwin** [comment]
A new branch to track this work: https://github.com/nationalparkservice/npmap.js/tree/cartodb-date-fields-interactivity.

**Comment by ryanjhodge** [comment]
They seem to have fixed this.  The two queries in my first post return the same number of columns and fieldnames now.  I merged and built the `cartodb-date-fields-interactivity` branch on my local machine and the YELL roads layer draws and the date fields show up in the popups.

**Comment by nateirwin** [comment]
Fixed. Thanks, @ryanjhodge!
