### ISSUE TITLE
Support points in geocoder

### ISSUE THREAD

**Issue by cwlawlis802** [nationalparkservice/npmap.js#297]
We need npmap.js' geocoder to support points so that units with only a `geom_point` and no `geom_poly` boundary, like OKCI https://github.com/nationalparkservice/places-data/issues/243, can be zoomed to appropriately in Park Tiles, Editor, etc.

**Comment by nateirwin** [comment]
@cwlawlis802: Where does this stand now that we're just going to be storing polygons in our parks table?

**Comment by cwlawlis802** [comment]
Each unit will still have a record in `parks_poly`, even if `geom_poly` is null. So, for units with only a point representation of a boundary, the ideal workflow would have the geocoder look at `parks_poly` and if `geom_poly` is null it would look to `geom_point` in `parks_point`.

Is this possible @nateirwin?

**Comment by nateirwin** [comment]
Yep, we can make this happen.

**Comment by nateirwin** [comment]
Ok, this is done. It will be deployed when I roll out the new version of the library. Potentially early next week, but more likely the following week.

Basically, the way this works now is a bounding box derived from `the_geom` is used if `the_geom` is not `null`. If it is `null`, the `latitude` and `longitude` values of the record are used to set the center of the map. If `the_geom` and `latitude`/`longitude` are `null`, the park will not be selectable in the dropdown.

You can test this with `Great Egg Harbor River` (which does not have `the_geom`, but has `latitude` and `longitude` values) and `Historic Jamestowne` (which does not have `the_geom` or `latitude`/`longitude`).
