### ISSUE TITLE
while testing, it occurs error in getting arcgisserver layer : SSL handshake failed

### ISSUE THREAD

**Issue by OliveLv** [nationalparkservice/npmap.js#302]
Error occuring in Windows is as follow:
![test-error2](https://cloud.githubusercontent.com/assets/8032480/12545132/ad530db8-c37a-11e5-84df-161ccd5e1db8.png)
I clicked page test/index.html, it fails 1 on chrome, while passing all on IE. Is that a problem? Should I configure nodejs as a https server? Thanks.

**Comment by nateirwin** [comment]
I just updated PhantomJS and Mocha, along with a number of other dependencies, and it seems to have resolved this issue.

Thanks for letting us know about it!
