### ISSUE TITLE
Problem with clustered and non-clustered point overlays?

### ISSUE THREAD

**Issue by frogmapr** [nationalparkservice/npmap.js#340]
I have a [map](http://www.nps.gov/maps/full.html?mapId=6796e967-0c84-45dc-99e8-c5cb0f715528) where I have a clustered point overlay and a non-clustered point overlay and the non clustered overlay is causing problems when trying to explode the clusters to see the points inside.  Here is a screenshot with the overlay order: 

![image](https://cloud.githubusercontent.com/assets/11652263/13709985/ff4313bc-e773-11e5-8bf3-a788d8c6c591.png)

You will see that the projects should display on top of the regional points.

But there are cases when they don't in the live map (see below)

![image](https://cloud.githubusercontent.com/assets/11652263/13710027/407d8bf0-e774-11e5-9eb4-ea3359de7ab2.png)

This makes it so I cannot see the points that lie inside the cluster.  This issue is not consistent and sometimes the cluster shows up on top of the other overlay such as this example (see below) 

![image](https://cloud.githubusercontent.com/assets/11652263/13710085/86ec7f7e-e774-11e5-94c6-a239b339f748.png)

Any thoughts on how to resolve this issue would be much appreciated!

**Comment by nateirwin** [comment]
Unfortunately, there's not much that can be done about the issue. Vector layers in Leaflet are not "aware" of each other, and clustering a layer can really highlight this problem.

One potential solution would be combining both layers into one. This may not, however, be possible for certain data types.
