### ISSUE TITLE
NPMap.config.L.getCenter(); error

### ISSUE THREAD

**Issue by cwlawlis802** [nationalparkservice/npmap.js#376]
When trying to grab coordinates from the NPMap.js geocoder example https://www.nps.gov/lib/npmap.js/3.0.7/examples/geocoder-control.html via `NPMap.config.L.getCenter();` the console reads an error:

```
VM112:1 Uncaught ReferenceError: NPMap is not defined(…)
  (anonymous function) @ VM112:1
```

cc @nateirwin

**Comment by nateirwin** [comment]
`NPMap.config.L.getCenter();` works fine for me in that example.

**Comment by cwlawlis802** [comment]
Weird, cleared cache + hard refresh and now it's working...

Sorry for the false alarm @nateirwin.
